# Check for new versions of dask on Conda Forge
name: PangeoNotebookUpdater

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
    #- cron:  "*/5 * * * *"

jobs:
  check-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: 'conda-forge/pangeo-notebook-feedstock'
          ref: 'main'
          
      - name: Get Todays Date
        id: calver
        run: echo "::set-output name=version::$(date +'%Y.%m.%d')"

      - name: Setup Micromamba
        uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-file: false
        
      # Until https://github.com/pangeo-bot/dispatcher/issues/7 fixed
      - name: Get latest Pangeo-dask
        id: latest_version_pangeodask
        run: | 
          VERSION=`micromamba repoquery search pangeo-dask -c conda-forge --json | jq '.result.pkgs[0].version'`
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Find and Replace pangeo-dask
        id: pangeodask
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: "meta.yaml"
          find: "pangeo-dask =.*"
          replace: "pangeo-dask =${{ steps.latest_version_pangeodask.outputs.version }}"

      - name: Get latest dask-labextension version
        id: latest_version_labext
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.3
        with:
          org: "conda-forge"
          package: "dask-labextension"

      - name: Find and Replace dask-labextension
        id: labextension
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: "meta.yaml"
          find: "dask-labextension =.*"
          replace: "dask-labextension =${{ steps.latest_version_labext.outputs.version }}"

      - name: Get latest ipywidgets version
        id: latest_version_ipywidgets
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.3
        with:
          org: "conda-forge"
          package: "ipywidgets"

      - name: Find and Replace ipywidgets
        id: ipywidgets
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: "meta.yaml"
          find: "ipywidgets =.*"
          replace: "ipywidgets =${{ steps.latest_version_ipywidgets.outputs.version }}"

      - name: Get latest jupyter-server-proxy version
        id: latest_version_server_proxy
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.3
        with:
          org: "conda-forge"
          package: "jupyter-server-proxy"

      - name: Find and Replace jupyter-server-proxy
        id: server_proxy
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: "meta.yaml"
          find: "jupyter-server-proxy =.*"
          replace: "jupyter-server-proxy =${{ steps.latest_version_server_proxy.outputs.version }}"

      - name: Get latest jupyterhub-singleuser version
        id: latest_version_jupyterhub_singleuser
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.3
        with:
          org: "conda-forge"
          package: "jupyterhub-singleuser"

      - name: Find and Replace jupyterhub-singleuser
        id: jupyterhub_singleuser
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: "meta.yaml"
          find: "jupyterhub-singleuser =.*"
          replace: "jupyterhub-singleuser =${{ steps.latest_version_jupyterhub_singleuser.outputs.version }}"

      - name: Get latest jupyterlab version
        id: latest_version_jupyterlab
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.3
        with:
          org: "conda-forge"
          package: "jupyterlab"

      - name: Find and Replace jupyterlab
        id: jupyterlab
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: "meta.yaml"
          find: "jupyterlab =.*"
          replace: "jupyterlab =${{ steps.latest_version_jupyterlab.outputs.version }}"

      - name: Get latest nbgitpuller version
        id: latest_version_nbgitpuller
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.3
        with:
          org: "conda-forge"
          package: "nbgitpuller"

      - name: Find and Replace nbgitpuller
        id: nbgitpuller
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: "meta.yaml"
          find: "nbgitpuller =.*"
          replace: "nbgitpuller =${{ steps.latest_version_nbgitpuller.outputs.version }}"

      - name: Find and Replace CalVer
        if: >
          steps.labextension.outputs.modifiedFiles > 0 || 
          steps.ipywidgets.outputs.modifiedFiles > 0 || 
          steps.server_proxy.outputs.modifiedFiles > 0 || 
          steps.jupyterhub_singleuser.outputs.modifiedFiles > 0 || 
          steps.jupyterlab.outputs.modifiedFiles > 0 || 
          steps.pangeodask.outputs.modifiedFiles > 0 || 
          steps.nbgitpuller.outputs.modifiedFiles > 0
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: "meta.yaml"
          find: "{% set version = \".*\" %}"
          replace: "{% set version = \"${{ steps.calver.outputs.version }}\" %}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update pangeo-notebook metapackage version(s)"
          title: "Update pangeo-notebook metapackage version(s)"
          branch: "upgrade-notebook-versions"
          push-to-fork: pangeo-bot/pangeo-notebook-feedstock
          token: ${{ secrets.PAT }}
          body: |
            It is very likely that one or more of the packages in this metapackage are out of date.
            https://github.com/pangeo-bot/dispatcher

            This PR updating one or more the following packages:
                -  dask-labextension -> `${{ steps.latest_version_labext.outputs.version }}`
                -  ipywidgets -> `${{ steps.latest_version_ipywidgets.outputs.version }}`
                -  jupyter-server-proxy -> `${{ steps.latest_version_server_proxy.outputs.version }}`
                -  jupyterhub-singleuser -> `${{ steps.latest_version_jupyterhub_singleuser.outputs.version }}`
                -  jupyterlab -> `${{ steps.latest_version_jupyterlab.outputs.version }}`
                -  pangeo-dask -> `${{ steps.latest_version_pangeodask.outputs.version }}`
                -  nbgitpuller -> `${{ steps.latest_version_nbgitpuller.outputs.version }}`

      - name: Keep scheduled jobs alive
        uses: gautamkrishnar/keepalive-workflow@v1
