# Check for new versions of dask on Conda Forge
name: PangeoDaskUpdater

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  check-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: 'conda-forge/pangeo-dask-feedstock'
          ref: 'main'
          
      - name: Get Todays Date
        id: calver
        run: echo "::set-output name=version::$(date +'%Y.%m.%d')"

      - name: Get latest dask version
        id: latest_version_dask
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.3
        with:
          org: "conda-forge"
          package: "dask"

      - name: Find and Replace Dask
        id: dask
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: "meta.yaml"
          find: "dask =.*"
          replace: "dask =${{ steps.latest_version_dask.outputs.version }}"

      - name: Get latest distributed version
        id: latest_version_distributed
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.3
        with:
          org: "conda-forge"
          package: "distributed"

      - name: Find and Replace Distributed
        id: distributed
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: "meta.yaml"
          find: "distributed =.*"
          replace: "distributed =${{ steps.latest_version_distributed.outputs.version }}"

      - name: Get latest dask-gateway version
        id: latest_version_gateway
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.3
        with:
          org: "conda-forge"
          package: "dask-gateway"

      - name: Find and Replace Dask-Gateway
        id: gateway
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: "meta.yaml"
          find: "dask-gateway =.*"
          replace: "dask-gateway =${{ steps.latest_version_gateway.outputs.version }}"

      - name: Find and Replace CalVer
        if: > 
          steps.dask.outputs.modifiedFiles > 0 || 
          steps.distributed.outputs.modifiedFiles > 0 || 
          steps.gateway.outputs.modifiedFiles > 0
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: "meta.yaml"
          find: "{% set version = \".*\" %}"
          replace: "{% set version = \"${{ steps.calver.outputs.version }}\" %}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update pangeo-dask metapackage version(s)"
          title: "Update pangeo-dask metapackage version(s)"
          branch: "upgrade-dask-versions"
          token: ${{ secrets.PAT }}
          push-to-fork: pangeo-bot/pangeo-dask-feedstock
          body: |
            It is very likely that one or more of the packages in this metapackage are out of date.
            https://github.com/pangeo-bot/dispatcher

            This PR updating one or more the following packages:
                -  dask =`${{ steps.latest_version_dask.outputs.version }}`
                -  distributed =`${{ steps.latest_version_distributed.outputs.version }}`
                -  dask-gateway =`${{ steps.latest_version_gateway.outputs.version }}`

      - name: Keep scheduled jobs alive
        uses: gautamkrishnar/keepalive-workflow@v1
